# Generated by Django 4.2.1 on 2023-05-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id_comment', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryModel',
            fields=[
                ('id_entry', models.BigAutoField(primary_key=True, serialize=False)),
                ('titles', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=40)),
                ('tags', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolModel',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_rol', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=40)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.rolmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id_profile', models.BigAutoField(primary_key=True, serialize=False)),
                ('biography', models.TextField()),
                ('image', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='LikesModel',
            fields=[
                ('id_like', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.commentsmodel')),
                ('id_entry', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.entrymodel')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.usermodel'),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='id_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.entrymodel'),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.usermodel'),
        ),
    ]
